# Generated by Django 3.0.3 on 2020-04-18 04:31

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0002_post_post_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
